version: '3.9'

services:

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    sysctls:
      net.core.somaxconn: 65535
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass secret --appendonly yes --daemonize no

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - ./data/mongo:/data/db

  mysql:
    container_name: mysql
    image: mysql:8.0.26
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo
      MYSQL_USER: db_user
      MYSQL_PASSWORD: secret
    privileged: true
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - default
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    restart: unless-stopped
    environment:
      ZOO_MY_ID: 1
    ports:
      - "2181:2181"
    networks:
      - default
    volumes:
      - ./data/zookeeper:/data

  zkui:
    image: juris/zkui
    container_name: zkui
    hostname: zkui
    restart: unless-stopped
    privileged: true
    environment:
      ZK_SERVER: zookeeper:2181
    ports:
      - "39001:9090"
    networks:
      - default
    depends_on:
      - zookeeper


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: secret
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  nats:
    container_name: nats
    image: nats:alpine
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - default

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
    ports:
      - "9092:9092"
    networks:
      - default
    volumes:
      - ./data/kafka:/kafka
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    restart: unless-stopped
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_BROKERS: kafka:9092
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    ports:
      - "39000:9000"
    networks:
      - default
    depends_on:
      - zookeeper
      - kafka

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: secret
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      node.name: es-node
      discovery.type: single-node
      bootstrap.memory_lock: "true"
    networks:
      - default
    ports:
      - "9200:9200"
      - "9300:9300"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - default

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-secret}
      GF_USERS_ALLOW_SIGN_UP: 'false'
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    external: true
    name: dev-network
