version: '3.9'

services:
  go-skeleton:
    image: ${GO_SKELETON_IMAGE}
    container_name: ${GO_SKELETON_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - ${GO_SKELETON_PORT}:8080
    networks:
      - default