version: '3.9'

services:

  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_TLS_PORT}:443
    volumes:
        - ${PWD}/conf.d/nginx.conf:/etc/nginx/conf.conf
        - ${PWD}/conf.d/sites:/etc/nginx/conf.d
    networks:
      - default

networks:
  default:
    name: ${NGINX_NETWORK}