version: '3.9'

services:

  mysql:
    image: ${MYSQL_IMAGE}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    privileged: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - default
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--lower_case_table_names=0",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    name: ${MYSQL_VOLUME}

networks:
  default:
    name: ${MYSQL_NETWORK}
