version: '3.9'

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.26
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: example
    privileged: true
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - default
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}

networks:
  default: {}